version: 3.7

services:
    kitsune-bot:
        image: docker.pkg.github.com/topisenpai/kitsune-bot:latest
        container_name: kitsune-bot
        restart: unless-stopped
        env_file:
            - conf.env
        networks:
            - kitsune-bot
        ports:
            - 80:80

networks:
    kitsune-bot:
        name:  kitsune-bot